// ========== البيانات المحلية للاختبار ==========

const LOCAL_DATA = [
    {childName: "مطرة", age: 5, gender: "أنثى", prevKG: false, fatherName: "أحمد الرشيد", phone: "997196942"},
    {childName: "نضال", age: 4, gender: "ذكر", prevKG: false, fatherName: "احمد العمر", phone: "997733923"},
    {childName: "فايز عباس", age: 4, gender: "ذكر", prevKG: false, fatherName: "عبد الجبار فايز", phone: "998562648"},
    {childName: "فاطمة", age: 4, gender: "أنثى", prevKG: false, fatherName: "محمد السعيد", phone: "996711823"},
    {childName: "حيدر", age: 3, gender: "ذكر", prevKG: false, fatherName: "علي حسن", phone: "995234567"},
    {childName: "خطاب", age: 5, gender: "ذكر", prevKG: false, fatherName: "سعيد خطاب", phone: "994567890"},
    {childName: "فاروق", age: 3, gender: "ذكر", prevKG: false, fatherName: "عمر فاروق", phone: "993456789"},
    {childName: "مرشد", age: 4, gender: "ذكر", prevKG: false, fatherName: "يوسف مرشد", phone: "992345678"},
    {childName: "ألين القدور", age: 4, gender: "أنثى", prevKG: true, fatherName: "خالد القدور", phone: "991234567"},
    {childName: "شروق", age: 5, gender: "أنثى", prevKG: true, fatherName: "أحمد شروق", phone: "990123456"},
    {childName: "يزن", age: 3, gender: "ذكر", prevKG: false, fatherName: "محمود يزن", phone: "999876543"},
    {childName: "بهاء الدين", age: 5, gender: "ذكر", prevKG: false, fatherName: "عبدالله بهاء", phone: "998765432"},
    {childName: "أروى", age: 3, gender: "أنثى", prevKG: false, fatherName: "سامي أروى", phone: "997654321"},
    {childName: "إبراهيم", age: 5, gender: "ذكر", prevKG: false, fatherName: "حسن إبراهيم", phone: "996543210"},
    {childName: "خطاب", age: 5, gender: "ذكر", prevKG: false, fatherName: "فهد خطاب", phone: "995432109"},
    {childName: "حمزة", age: 5, gender: "ذكر", prevKG: true, fatherName: "طارق حمزة", phone: "994321098"},
    {childName: "عائشة", age: 4, gender: "أنثى", prevKG: false, fatherName: "عمر عائشة", phone: "993210987"},
    {childName: "نوال", age: 4, gender: "أنثى", prevKG: true, fatherName: "سعد نوال", phone: "992109876"},
    {childName: "محمد مروان", age: 3, gender: "ذكر", prevKG: false, fatherName: "مروان أحمد", phone: "991098765"},
    {childName: "صهيب الخطيب", age: 5, gender: "ذكر", prevKG: false, fatherName: "خالد الخطيب", phone: "990987654"},
    {childName: "غصون شيخة", age: 5, gender: "أنثى", prevKG: false, fatherName: "محمد شيخة", phone: "999765432"},
    {childName: "ايمان", age: 5, gender: "أنثى", prevKG: false, fatherName: "عبدالرحمن ايمان", phone: "998654321"},
    {childName: "جنى الحنيني", age: 5, gender: "أنثى", prevKG: false, fatherName: "أحمد الحنيني", phone: "997543210"},
    {childName: "رحمة", age: 5, gender: "أنثى", prevKG: true, fatherName: "يوسف رحمة", phone: "996432109"},
    {childName: "محمد عبدو", age: 3, gender: "ذكر", prevKG: false, fatherName: "عبدو محمد", phone: "995321098"},
    {childName: "أنس", age: 5, gender: "ذكر", prevKG: false, fatherName: "سامي أنس", phone: "994210987"},
    {childName: "سلمى عمار الشبيب", age: 4, gender: "أنثى", prevKG: false, fatherName: "عمار الشبيب", phone: "993109876"},
    {childName: "لؤي عرعور", age: 3, gender: "ذكر", prevKG: false, fatherName: "فهد عرعور", phone: "992098765"},
    {childName: "خالد الأحمد", age: 5, gender: "ذكر", prevKG: false, fatherName: "علي الأحمد", phone: "991987654"},
    {childName: "نور الأحمد", age: 3, gender: "أنثى", prevKG: false, fatherName: "علي الأحمد", phone: "991987654"},
    {childName: "اسلام", age: 5, gender: "أنثى", prevKG: false, fatherName: "محمود اسلام", phone: "990876543"},
    {childName: "احمد", age: 4, gender: "ذكر", prevKG: false, fatherName: "خالد احمد", phone: "999654321"},
    {childName: "رنيم", age: 4, gender: "أنثى", prevKG: true, fatherName: "سعيد رنيم", phone: "998543210"},
    {childName: "وتين", age: 5, gender: "أنثى", prevKG: false, fatherName: "عمر وتين", phone: "997432109"},
    {childName: "يقين", age: 4, gender: "أنثى", prevKG: false, fatherName: "طارق يقين", phone: "996321098"},
    {childName: "هناء", age: 4, gender: "أنثى", prevKG: false, fatherName: "حسن هناء", phone: "995210987"},
    {childName: "عمار السليمان", age: 4, gender: "ذكر", prevKG: false, fatherName: "محمد السليمان", phone: "994109876"},
    {childName: "فاطمة النابو", age: 4, gender: "أنثى", prevKG: false, fatherName: "أحمد النابو", phone: "993098765"},
    {childName: "انس", age: 4, gender: "ذكر", prevKG: true, fatherName: "يوسف انس", phone: "992987654"},
    {childName: "عمر فتح الله", age: 3, gender: "ذكر", prevKG: false, fatherName: "سامي فتح الله", phone: "991876543"},
    {childName: "سيدرا علوش", age: 5, gender: "أنثى", prevKG: false, fatherName: "علي علوش", phone: "990765432"},
    {childName: "مصطفى علوش", age: 4, gender: "ذكر", prevKG: false, fatherName: "علي علوش", phone: "990765432"},
    // أطفال خارج النطاق (للتجربة)
    {childName: "طه خلف", age: 20, gender: "ذكر", prevKG: false, fatherName: "خلف الدين", phone: "997123456"},
    {childName: "سيدرا الجمال", age: 7, gender: "أنثى", prevKG: false, fatherName: "محمد الجمال", phone: "996234567"},
    {childName: "تسنيم الجمال", age: 7, gender: "أنثى", prevKG: false, fatherName: "محمد الجمال", phone: "996234567"},
    {childName: "عماد", age: 2, gender: "ذكر", prevKG: false, fatherName: "عبد الهادي رحيم", phone: "995345678"},
    {childName: "ريّان الدياب", age: 2, gender: "ذكر", prevKG: false, fatherName: "أحمد الدياب", phone: "994456789"},
    {childName: "خديجه", age: 9, gender: "أنثى", prevKG: false, fatherName: "سعيد خديجة", phone: "993567890"}
];